module ForemanThemeSatellite
  FOREMAN_BRAND = {
    /\bHTTP Proxy\b(?!-)/    => 'HTTP Proxy',
    /\bHTTP proxy\b(?!-)/    => 'HTTP Proxy',
    /\bIgnore Proxy\b(?!-)/  => 'Ignore Proxy',
    /\bIgnore proxy\b(?!-)/  => 'Ignore Proxy',
    /\bLeave this blank if no proxy is used\b(?!-)/ => 'Leave this blank if no proxy is used',
    /\bbypass proxy settings\b(?!-)/ => 'bypass proxy settings',
    /\bForeman\b(?!-)/       => 'Satellite',
    /\bforeman\b(?!-)/       => 'satellite',
    /\bsmart-proxy\b(?!-)/   => 'capsule',
    /\bSmart-proxy\b(?!-)/   => 'Capsule',
    /\bsmart proxies\b(?!-)/ => 'capsules',
    /\bSmart proxies\b(?!-)/ => 'Capsules',
    /\bsmart-proxies\b(?!-)/ => 'capsules',
    /\bSmart-proxies\b(?!-)/ => 'Capsules',
    /\bSmart Proxies\b(?!-)/ => 'Capsules',
    /\bSmart Proxy\b(?!-)/   => 'Capsule',
    /\bsmart proxy\b(?!-)/   => 'capsule',
    /\bSmart-Proxies\b(?!-)/ => 'Capsules',
    /\bSmart proxy\b(?!-)/   => 'Capsule',
    /\bSmart-Proxy\b(?!-)/   => 'Capsule',
    /\boVirt\b(?!-)/         => 'RHEV',
    /\bovirt\b(?!-)/         => 'RHEV',
    /\bOvirt\b(?!-)/         => 'RHEV',
    /\bFreeIPA\b(?!-)/       => 'Red Hat Identity Management',
    /\bOpenStack\b(?!-)/     => 'RHEL OpenStack Platform',
    /\bopenstack\b(?!-)/     => 'RHEL OpenStack Platform',
    /\bOpenstack\b(?!-)/     => 'RHEL OpenStack Platform',
    /\bProxy\b(?!-)/         => 'Capsule',
    /\bproxy\b(?!-)/         => 'Capsule',
    /\bProxies\b(?!-)/       => 'Capsules',
    /\bproxies\b(?!-)/       => 'Capsules' 
  }.freeze
end
